output_format = "i3bar"
colors = true
color_good = "#00AA00"

[[module]]
module = "memory"
format_degraded = "[$available / $percentage_available]"

[module.format]
full = "$used"

[[module]]
module = "battery"
number = 0
path = "/sys/class/power_supply/BAT%d/uevent"
format = "$status $percentage $remaining"
format_down = "No battery"
status_chr = "⚇ CHR"
status_bat = "⚡ BAT"
status_full = "☻ FULL"