output_format = "i3bar"
colors = true
color_good = "#00AA00"

[[module]]
module = "wireless"
interface = "wlan0"

[[module]]
module = "disk"
format = "/: $avail"

[[module]]
module = "memory"
format = "$used"
format_degraded = "[$available / $percentage_available]"

[[module]]
module = "battery"
number = 0
format = "$status $percentage $remaining"
format_down = "No battery"
status_chr = "⚇ CHR"
status_bat = "⚡ BAT"
status_full = "☻ FULL"
low_threshold = 15
threshold_type = "percentage"

[[module]]
module = "time"
title = "local"

[[module]]
module = "load_avg"
format = "Avg: $1min"

[[module]]
module = "path_exists"
title = "VPN"
path = "/non/existing/path"

[[module]]
module = "run_watch"
title = "rofi"
pidfile = "/var/run/user/1000/rofi.pid"

[[module]]
module = "file_contents"
title = "Uptime"
path = "/proc/uptime"
max_characters = 5