output_format = "i3bar"
colors = true
color_good = "#00AA00"

[[module]]
module = "memory"
format_degraded = "[$available / $percentage_available]"

[module.format]
full = "$used"

[[module]]
module = "battery"
number = 0
format = "$status $percentage $remaining"
format_down = "No battery"
status_chr = "⚇ CHR"
status_bat = "⚡ BAT"
status_full = "☻ FULL"
low_threshold = 50
threshold_type = "percentage"

[[module]]
module = "time"
title = "local"
format = "%Y-%m-%d %H:%M %Z"

[[module]]
module = "load_avg"
format = "Avg: $1min"