on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          #- x86_64-unknown-netbsd
          #- x86_64-unknown-freebsd
          #- x86_64-unknown-openbsd
          #- x86_64-unknown-dragonfly
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libasound2-dev
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"